let result;
console.log(`-----------------Task 1---------------------------------------------------`);
result = '3' + 2 ;
console.log(result);
console.log(`why ? :Result ${result} because it take 2 implicitly string and perform concationation on it.`);
result ='3'+ true;
console.log(result);
console.log(`why ? :Result ${result} because it take 3 implicitly string and perform concationation on it.`);

result= '3' + undefined ;
console.log(result);
console.log(`why ? :Result ${result} because it take 3 implicitly string and perform concationation on it with +operator..`);
result='3' +null ;
console.log(result);
console.log(`why ? :Result ${result} because it take 3 implicitly string and perform concationation on it with +operator.`);
console.log(`-------------------------------------------------------------------`);
result ='4' -  true ;
console.log(result);
console.log(`why ?: result ${result} because it take true(1) value boolean and result is 4-1=3`);
result =4 +  true ;
console.log(result);
console.log(`why ?: result ${result} because it take true(1) value boolean and result is 4+1=5`);
result =4 +  false ;
console.log(result);
console.log(`why ?: result ${result} because it take false(0) value boolean and result is 4+0=4`);
console.log(`------------------------------------------------------------------------------------`);
result ='4' -'2';
console.log(result);
console.log(`Why ? : Result ${result} because  it implicit numeric value . `);
result ='4' -2;
console.log(result);
console.log(`Why ? : Result ${result} because  it implicit numeric value . `);
result ='4' *2;
console.log(result);
console.log(`Why ? : Result ${result} because  it implicit numeric value . `);
result ='4' /2;
console.log(result);
console.log(`Why ? : Result ${result} because  it implicit numeric value . `);

