console.log(0=='');
console.log(`why ?: Because it takes implicitly number`);
console.log(0=='0');
console.log(`why ?: Because it takes implicitly number`);
console.log(0==false);
console.log(`why ?: Because it takes boolean implicitly number `);
console.log(null==undefined);
console.log(`why ?: Because it takes implicitly same type`);
console.log(1==[1]);
console.log(`why ?: Because it takes implicitly number`);
console.log(1==true);
console.log(`why ?: Because it takes boolean  implicitly number`);
console.log(1=='1');
console.log(`why ?: Because it takes implicitly number`);